spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneymanager?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 170804
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${BREVO_FROM_EMAIL}
    protocol: smtp
app:
  mail:
    from: ${BREVO_FROM_EMAIL}

jwt:
  signerKey: "RIDdDrZ4IzV5zpP1zc7lSqhR71AWXxXTjZnYqov5TAyoz8wHHp+mOr0eg94WwxCk"
money:
  manager:
    frontend:
      url: http://localhost:5173