spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneymanager?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 170804
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        from: ${BREVO_FROM_EMAIL}
    protocol: smtp

jwt:
  signerKey: ${JWT_SIGNER_KEY:dev-local-only-change-me}

app:
  mail:
    from: ${BREVO_FROM_EMAIL}
  activation:
    url: ${MONEY_MANAGER_BACKEND_URL}

money:
  manager:
    frontend:
      url: ${MONEY_MANAGER_FRONTEND_URL}
